import type { Metadata } from "next";
import { Noto_Sans_JP, Shippori_Mincho } from "next/font/google"; // Removed Geist as per new design
import "./styles.css";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const shipporiMincho = Shippori_Mincho({
  variable: "--font-shippori-mincho", // Correct variable name for serif
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header } from "@/components/common/Header";
import { Footer } from "@/components/common/Footer";
import { BottomNav } from "@/components/common/BottomNav";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} ${shipporiMincho.variable} antialiased bg-[#F8F9FA] text-[#1A1A1B] pt-0 flex flex-col min-h-screen font-sans`}
      >
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        {/* pt-0 because Hero often goes under header or handles its own spacing. Resetting default top padding. */}
        <Header />
        <main className="flex-grow pb-16 md:pb-0">
          {children}
        </main>
        <Footer />
        <BottomNav />
      </body>
    </html>
  );
}
