import { AbsoluteFill, useCurrentFrame, useVideoConfig, interpolate, Audio, staticFile, getInputProps, Img } from 'remotion';
import scriptData from './video-script.json';

// Define Types based on Video Director Output
type Scene = {
    scene_id: number;
    section_type: string; // 'hook', 'retention', 'logic', 'cta'
    duration_sec: number;
    narration_text: string;
    screen_text: string;
    visual_prompt: string;
};

type VideoMetadata = {
    total_duration: number;
    bgm_style: string;
};

type VideoScript = {
    project_title: string;
    scenes: Scene[];
    metadata: VideoMetadata;
};

// Available Background Images (Generated by AI)
const SCENE_IMAGES: { [key: number]: string } = {
    1: "scenes/scene_1_hook_1768924250486.png",
    2: "scenes/scene_2_retention_1768924270014.png",
    3: "scenes/scene_3_retention_1768924288132.png",
    4: "scenes/scene_4_logic_1768924321549.png",
    5: "scenes/scene_5_logic_1768924337792.png",
    6: "scenes/scene_6_logic_1768924355281.png",
    7: "scenes/scene_7_logic_1768924388702.png",
    // Fallbacks for failed generations (Quota limit)
    8: "scenes/scene_1_hook_1768924250486.png", // Reuse professional face for CTA
    9: "scenes/scene_6_logic_1768924355281.png", // Reuse Gold for Future
};

const scriptSource = scriptData as VideoScript;

export const MyVideo = () => {
    const frame = useCurrentFrame();
    const { fps } = useVideoConfig();

    const inputProps = getInputProps();
    let script: VideoScript = scriptSource;

    if (inputProps.scriptJson) {
        try {
            script = JSON.parse(inputProps.scriptJson as string);
        } catch (e) {
            console.error("Failed to parse scriptJson prop, using bundled.", e);
        }
    }

    // Calculate active scene
    let currentScene: Scene | null = null;
    let accumulatedFrames = 0;
    let sceneStartFrame = 0;
    let sceneIndex = 0;

    for (let i = 0; i < script.scenes.length; i++) {
        const scene = script.scenes[i];
        const durationFrames = scene.duration_sec * fps;
        if (frame >= accumulatedFrames && frame < accumulatedFrames + durationFrames) {
            currentScene = scene;
            sceneStartFrame = accumulatedFrames;
            sceneIndex = i;
            break;
        }
        accumulatedFrames += durationFrames;
    }

    if (!currentScene && script.scenes.length > 0) {
        currentScene = script.scenes[script.scenes.length - 1];
        sceneIndex = script.scenes.length - 1;
    }

    if (!currentScene) return null;

    // Animation details
    const timeInScene = frame - sceneStartFrame;
    const durationFrames = currentScene.duration_sec * fps;

    // Smooth Fade
    const opacity = interpolate(
        timeInScene,
        [0, 15, durationFrames - 15, durationFrames],
        [0, 1, 1, 0],
        { extrapolateRight: 'clamp' }
    );

    const translateY = interpolate(
        timeInScene,
        [0, 30],
        [20, 0],
        { extrapolateRight: 'clamp' }
    );

    // Ken Burns Effect
    const scale = sceneIndex % 2 === 0
        ? interpolate(timeInScene, [0, durationFrames], [1.1, 1.25])
        : interpolate(timeInScene, [0, durationFrames], [1.25, 1.1]);

    // Select Background Image
    // Use mapped image or fallback to first one
    const bgImageName = SCENE_IMAGES[currentScene.scene_id] || SCENE_IMAGES[1];
    const bgImage = staticFile(bgImageName);

    const audio = staticFile("audio.mp3");

    // Dynamic Overlay Colors
    const getOverlayColor = (type: string) => {
        switch (type) {
            case 'hook': return 'rgba(60, 0, 0, 0.7)'; // Red Tint
            case 'retention': return 'rgba(0, 0, 0, 0.8)'; // Dark
            case 'logic': return 'rgba(0, 20, 50, 0.7)'; // Blue Tint
            case 'cta': return 'rgba(255, 255, 255, 0.9)'; // White
            default: return 'rgba(0, 0, 0, 0.8)';
        }
    };

    const overlayColor = getOverlayColor(currentScene.section_type);
    const textColor = currentScene.section_type === 'cta' ? '#000000' : '#ffffff';

    return (
        <AbsoluteFill style={{ backgroundColor: '#000', overflow: 'hidden' }}>
            <Audio src={audio} />

            {/* Background Image Layer */}
            <AbsoluteFill style={{ transform: `scale(${scale})` }}>
                <Img src={bgImage} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
            </AbsoluteFill>

            {/* Overlay Layer */}
            <AbsoluteFill style={{ backgroundColor: overlayColor }} />

            {/* Content Layer */}
            <AbsoluteFill style={{
                justifyContent: 'center',
                alignItems: 'center',
                padding: '0 60px'
            }}>
                <div
                    style={{
                        fontFamily: '"Shippori Mincho", "Times New Roman", serif',
                        color: textColor,
                        fontWeight: 'bold',
                        opacity,
                        transform: `translateY(${translateY}px)`,
                        textAlign: 'center',
                        lineHeight: 1.5,
                        display: 'flex',
                        flexDirection: 'column',
                        gap: '40px',
                        width: '100%',
                        textShadow: currentScene.section_type !== 'cta' ? '0px 4px 20px rgba(0,0,0,0.8)' : 'none'
                    }}
                >
                    {/* Visual Label */}
                    <div style={{ fontSize: '24px', opacity: 0.8, textTransform: 'uppercase', letterSpacing: '0.2em' }}>
                        {currentScene.section_type}
                    </div>

                    {/* Main Text */}
                    <div style={{
                        fontSize: '68px',
                        letterSpacing: '0.05em',
                        wordBreak: 'break-word',
                        whiteSpace: 'pre-wrap',
                    }}>
                        {currentScene.screen_text}
                    </div>
                </div>
            </AbsoluteFill>
        </AbsoluteFill>
    );
};
